{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rowanmcalpin.nextftc",
    "module": "core",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.8.0.aar",
          "url": "core-0.8.0.aar",
          "size": 62680,
          "sha512": "518cd2b1b5e9c157d7b37e98a9257e035000d9f9b6989768bab53eb2047f7d57fcfb05f0897af295aa47d794ed08dba30e836b0180d4a788f7d1f9c6cf7b53ce",
          "sha256": "6346d9c87c9d3e444d459034e9215b8bdede922cf4bec5c36bb6bc76b481c809",
          "sha1": "4c9e0a3d24e7d770c0d1e1df91b321ed9248388c",
          "md5": "66f644f27b6972f02ea7f97f1256ae5f"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.8.0.aar",
          "url": "core-0.8.0.aar",
          "size": 62680,
          "sha512": "518cd2b1b5e9c157d7b37e98a9257e035000d9f9b6989768bab53eb2047f7d57fcfb05f0897af295aa47d794ed08dba30e836b0180d4a788f7d1f9c6cf7b53ce",
          "sha256": "6346d9c87c9d3e444d459034e9215b8bdede922cf4bec5c36bb6bc76b481c809",
          "sha1": "4c9e0a3d24e7d770c0d1e1df91b321ed9248388c",
          "md5": "66f644f27b6972f02ea7f97f1256ae5f"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-0.8.0-sources.jar",
          "url": "core-0.8.0-sources.jar",
          "size": 70145,
          "sha512": "71b6c56c79d210516c9dff1735e28467293d6de62dcf0ccf9a2f92557297e5414a52fa6d856f0598640a869cb25bb7cc82f3c6092e0819711c493784675e3f5d",
          "sha256": "0dae09190dd037ed9ec5fccc39c8680b222ecb8343d6d06214db3c6dfe7cb1d2",
          "sha1": "5f5193fa7cd1a6b9dcc3ff3e37c13d2544f33044",
          "md5": "fe53d38bab30e52aa9e8250d502d711b"
        }
      ]
    }
  ]
}
